
class RowNotFound_Exception(Exception):
    pass


class UsernameExists(Exception):
    pass
